// content/industrial-cases.js — Datos educativos, sin dimensionamiento de equipos.
(function (N) {
  'use strict';
  N.content.industrialCriteria = [
    { id: 'power', name: 'Potencia', question: '¿Qué esfuerzo y ritmo necesita la tarea?', explanation: 'Potencia es energía transferida por unidad de tiempo. No es lo mismo que fuerza o par (esfuerzo de giro).', decision: 'Una carga grande puede necesitar más par o una transmisión. No se elige un motor solo por su velocidad.' },
    { id: 'control', name: 'Controlabilidad', question: '¿Solo encender, regular o corregir el movimiento?', explanation: 'Es la facilidad para mandar y ajustar la acción. La realimentación compara lo pedido con lo medido.', decision: 'Un contactor enciende; un variador regula; un servo corrige posición con un sensor. Más control añade componentes y ajustes.' },
    { id: 'size', name: 'Peso / volumen', question: '¿Cuánto espacio ocupa el sistema completo?', explanation: 'Cuenta el actuador y también su fuente, transmisión, válvulas y electrónica.', decision: 'Un cilindro compacto puede necesitar un compresor o una central grande. No compares solo el cuerpo visible.' },
    { id: 'precision', name: 'Precisión', question: '¿Hay que llegar a una posición y comprobarla?', explanation: 'Ordenar pasos no confirma la posición real. Exactitud, repetibilidad y resolución no son lo mismo.', decision: 'Paso a paso para incrementos con margen de carga; servo si el ejemplo exige posición verificada mediante realimentación.' },
    { id: 'speed', name: 'Velocidad', question: '¿Qué rapidez y aceleración exige el ciclo?', explanation: 'Girar rápido no implica acelerar una carga rápidamente. El par disponible puede bajar con la velocidad.', decision: 'Un paso a paso sencillo puede servir a ritmo moderado. Para movimientos rápidos y corregidos suele evaluarse un servo.' },
    { id: 'maintenance', name: 'Mantenimiento', question: '¿Qué se desgasta, ensucia o puede fugar?', explanation: 'Escobillas, rodamientos, sellos, filtros y conexiones requieren atención según el servicio.', decision: 'El DC con escobillas exige revisar desgaste; neumática e hidráulica añaden tratamiento del fluido y control de fugas.' },
    { id: 'cost', name: 'Costo', question: '¿Cuánto cuesta adquirir y mantener la solución?', explanation: 'Incluye fuente, controlador, transmisión, energía, repuestos y paradas; no solo el precio del actuador.', decision: 'El paso a paso puede simplificar una mesa ligera; pagar por un servo tiene sentido cuando la realimentación y dinámica se necesitan.' }
  ];
  // Los límites describen SOLO estos conjuntos de ejemplo; no familias universales.
  N.content.industrialActuators = [
    { id: 'ac', name: 'Motor AC + variador', sources: ['ac'], precision: 1, load: 3, speed: 3, cost: 2, mechanical: true,
      traits: ['Giro continuo con carga alta en este ejemplo', 'Variador: ajusta frecuencia y velocidad', 'Motor + variador + transmisión', 'Sin lazo de posición', 'Continua; aceleración por configurar', 'Rodamientos y ventilación', 'Medio'], assumption: 'Motor de inducción y variador compatibles con la red; transmisión y protecciones por verificar.' },
    { id: 'dc', name: 'Motor DC con escobillas', sources: ['dc'], precision: 1, load: 1, speed: 2, cost: 1, mechanical: true,
      traits: ['Pequeña carga en este conjunto', 'PWM: pulsos que regulan tensión media', 'Compacto; requiere etapa de potencia', 'Sin sensor de posición en el ejemplo', 'Ritmo moderado', 'Desgaste de escobillas', 'Bajo'], assumption: 'Motor y driver a 24 V DC del ejemplo; PWM no garantiza posición ni velocidad exacta bajo carga.' },
    { id: 'stepper', name: 'Motor paso a paso', sources: ['dc'], precision: 2, load: 2, speed: 2, cost: 1, mechanical: true,
      traits: ['Carga ligera o media con margen', 'Driver: convierte impulsos en fases', 'Motor + driver + mecanismo', 'Incrementos; no confirma llegada', 'Lento o moderado', 'Revisar transmisión y calentamiento', 'Bajo'], assumption: 'Driver compatible con 24 V DC, referencia inicial y margen de par. En lazo abierto puede perder pasos.' },
    { id: 'servo', name: 'Servomotor + encoder', sources: ['ac'], precision: 3, load: 2, speed: 3, cost: 3, mechanical: true,
      traits: ['Carga ligera o media en este conjunto', 'Lazo cerrado: corrige el error medido', 'Motor + driver + sensor + transmisión', 'Posición medida con encoder', 'Rápida con control de aceleración', 'Revisar sensor, ajuste y transmisión', 'Alto'], assumption: 'Servo industrial AC del catálogo educativo. Encoder significa sensor de posición; no elimina holgura ni garantiza seguridad.' },
    { id: 'pneumatic', name: 'Cilindro neumático', sources: ['air', 'dc'], precision: 1, load: 2, speed: 3, cost: 1, mechanical: true,
      traits: ['Empuje ligero o medio del ejemplo', 'Válvula y finales de carrera', 'Cilindro pequeño; compresor aparte', 'Dos extremos, no posición intermedia', 'Maniobra rápida', 'Fugas, filtros y sellos', 'Bajo si ya existe aire'], assumption: 'Aire acondicionado y válvula de mando a 24 V DC disponibles. Se supone carrera entre topes, no posicionamiento continuo.' },
    { id: 'hydraulic', name: 'Cilindro hidráulico', sources: ['hydraulic', 'dc'], precision: 1, load: 3, speed: 2, cost: 3, mechanical: true,
      traits: ['Empuje alto en este ejemplo', 'Válvula direccional; sin servoválvula', 'Cilindro + central + tuberías', 'Entre extremos; sin lazo de posición', 'Ritmo lento o moderado', 'Limpieza del aceite, sellos y fugas', 'Alto'], assumption: 'Central hidráulica operativa y mando a 24 V DC. No se modelan presión, caudal ni energía acumulada.' },
    { id: 'solenoid', name: 'Electroválvula solenoide', sources: ['dc'], precision: 1, load: 1, speed: 3, cost: 1, mechanical: false,
      traits: ['Abre un paso; no aporta bombeo', 'Orden abrir / cerrar', 'Válvula + bobina + driver', 'Dos estados, no dosificación exacta', 'Conmutación; respuesta por verificar', 'Asiento, sellos y bobina', 'Bajo'], assumption: 'Válvula 2/2 normalmente cerrada de acción directa a 24 V DC. Fluido compatible y presión favorable ya disponibles.' },
    { id: 'pump', name: 'Motobomba', sources: ['ac'], precision: 1, load: 1, speed: 2, cost: 2, mechanical: false,
      traits: ['Aporta energía al líquido', 'Contactor o variador del motor', 'Motor + bomba + tubería', 'No mide ni dosifica por sí sola', 'Caudal depende del circuito', 'Sellos, aspiración y rodamientos', 'Medio'], assumption: 'Motobomba centrífuga AC, cebada, con líquido y aspiración adecuados. No se calcula caudal ni altura.' },
    { id: 'pilot', name: 'Piloto luminoso', sources: ['dc'], precision: 1, load: 1, speed: 3, cost: 1, mechanical: false,
      traits: ['Emite luz, no esfuerzo mecánico', 'Encender / apagar', 'Indicador compacto de panel', 'Comunica un estado', 'Aviso visual', 'Limpieza y comprobación visible', 'Bajo'], assumption: 'Piloto de panel a 24 V DC con texto equivalente. Un piloto encendido no demuestra que una máquina se haya detenido.' },
    { id: 'buzzer', name: 'Zumbador', sources: ['dc'], precision: 1, load: 1, speed: 3, cost: 1, mechanical: false,
      traits: ['Emite sonido, no movimiento útil', 'Orden de aviso', 'Dispositivo compacto', 'Comunica un estado', 'Aviso acústico', 'Comprobar audibilidad y accesibilidad', 'Bajo'], assumption: 'Zumbador activo a 24 V DC, acompañado de aviso visible. Este banco no reproduce audio ni diseña alarmas de seguridad.' }
  ];
  N.content.industrialCases = [
    { id: 'bandas', name: 'Bandas', tag: 'TRANSPORTAR', drawing: 'belt', defaults: { precision: 'basic', load: 'medium', budget: 'medium', speed: 'normal' },
      works: 'El motor gira un rodillo y la banda arrastra las piezas. Una transmisión adapta el giro y el esfuerzo.', application: 'Transportar cajas entre dos puestos de una línea.', why: 'AC con variador es una base para giro continuo. DC sirve para una banda pequeña; paso a paso o servo si la tarea cambia a avance por posiciones.', others: 'Un cilindro solo recorre una carrera. Un solenoide no sostiene el giro continuo de la banda.', candidates: [{ id: 'ac', fit: 5 }, { id: 'dc', fit: 4 }, { id: 'stepper', fit: 3 }, { id: 'servo', fit: 3 }] },
    { id: 'robots', name: 'Robots', tag: 'COORDINAR', drawing: 'robot', defaults: { precision: 'verified', load: 'medium', budget: 'high', speed: 'fast' },
      works: 'Cada articulación mueve un eje. En un servo, el controlador compara la posición pedida con la medida y corrige el error.', application: 'Colocar una pieza con un brazo ligero de varios ejes.', why: 'El servo del ejemplo combina posición medida y cambios rápidos. Un paso a paso queda para un robot didáctico lento que admita no verificar cada movimiento.', others: 'Un DC sin encoder no sabe dónde está. Un cilindro entre topes no sustituye la coordinación de articulaciones.', candidates: [{ id: 'servo', fit: 5 }, { id: 'stepper', fit: 3 }] },
    { id: 'bombeo', name: 'Bombeo', tag: 'TRANSFERIR', drawing: 'pump', defaults: { precision: 'basic', load: 'light', budget: 'medium', speed: 'normal' },
      works: 'El motor hace girar una bomba que entrega energía al líquido. El circuito determina el caudal junto con la curva de la bomba.', application: 'Transferir agua desde un depósito a otro.', why: 'La motobomba produce la transferencia. Se supone líquido disponible, cebado y una salida apropiada.', others: 'Una electroválvula solo abre el camino. Un cilindro hidráulico mueve su vástago; no equivale a una bomba de proceso.', candidates: [{ id: 'pump', fit: 5 }] },
    { id: 'control-liquidos', name: 'Control líquidos', tag: 'ADMITIR', drawing: 'tank', defaults: { precision: 'basic', load: 'light', budget: 'low', speed: 'normal' },
      works: 'Un sensor informa del nivel; la lógica manda abrir o cerrar una válvula de entrada. La válvula no mide el nivel.', application: 'Permitir llenado desde una línea ya presurizada y detener la admisión al alcanzar una referencia.', why: 'Una electroválvula sirve para admisión de dos estados, no para prometer un volumen exacto. La regulación fina necesitaría más instrumentación.', others: 'El piloto solo informa. Una bomba cambia la energía del circuito: no sustituye automáticamente el cierre de una línea presurizada.', candidates: [{ id: 'solenoid', fit: 5 }] },
    { id: 'electrovalvulas', name: 'Electroválvulas', tag: 'CONMUTAR', drawing: 'valve', defaults: { precision: 'basic', load: 'light', budget: 'low', speed: 'fast' },
      works: 'La bobina atrae un émbolo y cambia el paso. En este ejemplo 2/2 hay dos vías y dos posiciones; el resorte cierra al retirar la orden.', application: 'Habilitar agua de enjuague durante una etapa de lavado.', why: 'El solenoide transforma la orden eléctrica en apertura. Abrir no crea presión ni garantiza flujo.', others: 'Un motor necesitaría una válvula y transmisión adecuadas. Un zumbador no modifica el paso del fluido.', candidates: [{ id: 'solenoid', fit: 5 }] },
    { id: 'alarmas', name: 'Alarmas', tag: 'AVISAR', drawing: 'alarm', defaults: { precision: 'basic', load: 'light', budget: 'low', speed: 'normal' },
      works: 'La lógica activa luz o sonido para comunicar una condición. El aviso no corrige por sí mismo la causa.', application: 'Indicar fin de ciclo con piloto y llamar la atención con zumbador si no se mira el panel.', why: 'El zumbador avisa sin mirada directa; el piloto ofrece confirmación visual. Son complementarios, no sustitutos universales.', others: 'Un motor mueve, pero no es un dispositivo de señalización. Esta comparación no diseña un sistema de alarma de seguridad.', candidates: [{ id: 'buzzer', fit: 5 }, { id: 'pilot', fit: 5 }] },
    { id: 'ventiladores', name: 'Ventiladores', tag: 'VENTILAR', drawing: 'fan', defaults: { precision: 'basic', load: 'light', budget: 'medium', speed: 'normal' },
      works: 'Un motor gira las aspas y mueve aire. La carcasa y el circuito influyen en el flujo.', application: 'Renovar aire de un gabinete o aportar ventilación a un recinto.', why: 'AC encaja en servicio continuo; DC del ejemplo permite un equipo pequeño con alimentación de 24 V.', others: 'El paso a paso añade control incremental que no se necesita. Una válvula no genera el movimiento de las aspas.', candidates: [{ id: 'ac', fit: 5 }, { id: 'dc', fit: 4 }] },
    { id: 'extractores', name: 'Extractores', tag: 'EXTRAER', drawing: 'extractor', defaults: { precision: 'basic', load: 'medium', budget: 'medium', speed: 'normal' },
      works: 'El motor impulsa una turbina que extrae aire a través de un conducto. Filtros y pérdidas del conducto cambian el punto de trabajo.', application: 'Extraer aire de una zona de proceso no peligrosa en el ejemplo.', why: 'El motor AC con variador permite adaptar el giro continuo. La variante DC representa solo un extractor pequeño.', others: 'Un cilindro no produce giro continuo. Para polvo combustible o atmósferas peligrosas hacen falta equipos certificados y evaluación específica.', candidates: [{ id: 'ac', fit: 5 }, { id: 'dc', fit: 3 }] },
    { id: 'mezcladoras', name: 'Mezcladoras', tag: 'MEZCLAR', drawing: 'mixer', defaults: { precision: 'basic', load: 'heavy', budget: 'medium', speed: 'slow' },
      works: 'El motor y un reductor hacen girar paletas. El esfuerzo cambia con viscosidad, cantidad y arranque del material.', application: 'Mezclar un producto dentro de un tanque.', why: 'AC con transmisión es una base para servicio continuo. Un DC pequeño se limita aquí a una mezcla ligera de banco.', others: 'La motobomba puede recircular, pero no reemplaza las paletas en esta tarea. Más velocidad no resuelve falta de par.', candidates: [{ id: 'ac', fit: 5 }, { id: 'dc', fit: 3 }] },
    { id: 'posicionamiento', name: 'Posicionamiento', tag: 'UBICAR', drawing: 'position', defaults: { precision: 'indexed', load: 'light', budget: 'low', speed: 'normal' },
      works: 'Un motor gira un husillo que desplaza una mesa. El paso de avance convierte vueltas en distancia; holgura y carga alteran el resultado.', application: 'Mover una mesa ligera entre ubicaciones de trabajo.', why: 'Paso a paso para incrementos a ritmo moderado y con margen. Servo si se exige medir y corregir la posición o aumentar la dinámica.', others: 'Contar impulsos no detecta pasos perdidos. Un DC sin encoder y un cilindro entre topes no ofrecen el mismo posicionamiento intermedio.', candidates: [{ id: 'stepper', fit: 5 }, { id: 'servo', fit: 4 }] },
    { id: 'procesos-automatizados', name: 'Procesos automatizados', tag: 'EMPUJAR', drawing: 'process', defaults: { precision: 'basic', load: 'medium', budget: 'low', speed: 'fast' },
      works: 'El controlador coordina detección, sujeción y expulsión. Aquí se selecciona solo el actuador de empuje entre dos extremos, no toda la línea.', application: 'Expulsar una pieza con neumática; comparar con una maniobra de empuje lento y carga alta mediante hidráulica.', why: 'Neumática para maniobra rápida con aire existente. Hidráulica para empuje alto del ejemplo si existe central y se acepta mayor costo.', others: 'El solenoide manda una válvula, pero no sustituye al cilindro que empuja. Servo y husillo requerirían otra solución mecánica fuera de este catálogo.', candidates: [{ id: 'pneumatic', fit: 5 }, { id: 'hydraulic', fit: 4 }] }
  ];
}(window.NEXO));
