// content/integration.js
window.NEXO.content.integracion = {
  title: 'La señal decide.\nLa acción responde.',
  subtitle: 'Conecta sensor, controlador y actuador. Cambia una entrada y comprueba si la acción corrige el proceso.',
  objectives: ['Seguir medida, decisión, potencia y respuesta.', 'Predecir qué cambia al abrir el lazo.', 'Elegir componentes que actúan sobre el mismo proceso.'],
  note: 'Tres bancos locales. Comienzan en pausa y no se conectan a ningún equipo.',
  sections: [
    { title: 'Una cadena con retorno', text: 'El sensor mide. El controlador compara. El driver entrega energía. El actuador cambia el proceso. En lazo cerrado, ese cambio vuelve a medirse.' },
    { title: 'Construye una conexión coherente', text: 'No basta con unir tres nombres: la acción tiene que modificar lo que quieres controlar.' },
    { title: 'Decide ante un caso real', text: 'Predice antes de responder. La explicación importa más que memorizar una etiqueta.' }
  ],
  cases: {
    temperature: { title: 'Cámara térmica / NTC → ventilador', short: 'Más calor no exige mover un sensor: la temperatura cambia con el tiempo.', prediction: 'Predice: con el mismo calor, ¿enfriará más el ventilador encendido? Compara cerrado y abierto con la orden manual apagada.', detail: 'La NTC transforma temperatura en resistencia; el acondicionamiento permite estimar °C. El controlador enciende por encima del umbral y apaga por debajo de umbral menos histéresis. La histéresis evita cambios repetidos cerca del límite. El driver alimenta un motor; la señal de la NTC no lo alimenta. Aporte y ventilación compiten: incluso encendido, el ventilador puede acercarse a un equilibrio en vez de enfriar indefinidamente.' },
    metal: { title: 'Banda de inspección / inductivo → motor', short: 'La pieza viaja hasta un sensor fijo. Detectar metal corta el avance.', prediction: 'Predice: ¿se detendrá una pieza de plástico? Prueba metal en cerrado; luego abre el lazo y ordena avanzar para cruzar la estación.', detail: 'El inductivo detecta presencia metálica a corta distancia; no mide la composición de todo material ni la posición continua. La ventana fija está entre 500 y 520 mm y la pieza mide 60 mm. La posición mostrada es la del modelo, no una salida analógica del sensor. Un motor DC, una reducción 60:1 y un rodillo de radio 20 mm mueven la banda. La parada ideal es instantánea: no se modelan inercia, frenado, retardos ni una función certificada de seguridad.' },
    pressure: { title: 'Depósito presurizado / transmisor → alivio', short: 'Entra aire: sube la presión. Abre el alivio: el depósito descarga.', prediction: 'Predice: con el mismo aporte, ¿qué ocurre al abrir manualmente la válvula? Compara 4–20 mA, presión y orden de bobina.', detail: 'El transmisor escala 0–400 kPa absolutos a 4–20 mA. Se alivia hacia una atmósfera de 101 kPa. Abrir la electroválvula aumenta la descarga; cerrarla no detiene el aporte. El modelo concentrado tiene fuga pasiva y un límite didáctico de 400 kPa: ese límite no representa protección real. Con poco aporte, la presión puede no alcanzar el umbral. Una electroválvula de esta demostración no sustituye una válvula de seguridad certificada.' }
  },
  questions: [
    { question: 'La cámara está a 39 °C, el umbral es 35 °C y el lazo está cerrado. ¿Qué debe ocurrir?', options: ['El sensor alimenta directamente el ventilador.', 'El controlador activa el driver; el ventilador aumenta la disipación.', 'La temperatura salta de inmediato a 35 °C.'], answer: 1, why: 'Medir, decidir y aportar energía son tareas distintas. La temperatura responde de forma gradual al balance térmico.' },
    { question: 'Cambias a lazo abierto y dejas el ventilador manual apagado. La temperatura supera el umbral. ¿Se encenderá solo?', options: ['No: la medida se muestra, pero no gobierna la salida.', 'Sí, porque tener sensor siempre cierra el lazo.', 'Solo si la resistencia de la NTC es cero.'], answer: 0, why: 'En abierto manda la orden manual. Mostrar la medida no basta: debe participar en la decisión para cerrar el lazo.' },
    { question: 'Umbral térmico 35 °C, histéresis 2 °C. El ventilador estaba encendido y la medida baja a 34 °C. ¿Qué orden se conserva?', options: ['Apagado inmediato.', 'Se alterna cada paso.', 'Encendido hasta bajar de 33 °C.'], answer: 2, why: 'Entre 33 y 35 °C, incluidos los extremos, el controlador conserva la orden anterior. La memoria de la banda reduce conmutaciones.' },
    { question: 'Una caja de plástico cruza el sensor inductivo de la banda en lazo cerrado. ¿Cuál es la predicción de este banco?', options: ['Se detiene porque el inductivo detecta todos los sólidos.', 'Sigue avanzando: no se detecta metal.', 'La salida inductiva toma un valor de presión.'], answer: 1, why: 'El inductivo responde a un objetivo metálico dentro de su zona. Para plástico puede ser necesaria otra tecnología y una prueba con el material real.' },
    { question: 'La pieza metálica se ha detenido ante el sensor. ¿Cómo comprobar que la parada dependía de esa detección?', options: ['Abrir el lazo y ordenar avanzar; observar que la pieza cruza.', 'Cambiar únicamente el color de la pieza.', 'Aumentar el umbral de temperatura de la cámara.'], answer: 0, why: 'Al abrir el lazo se elimina la detección de la decisión. La orden manual puede entonces mover la pieza aunque siga detectada.' },
    { question: 'El depósito supera el umbral y la válvula de alivio abre. Con el mismo aporte, ¿qué comparación esperas?', options: ['La presión sube más que con la válvula cerrada.', 'La presión absoluta se vuelve negativa de inmediato.', 'La descarga hace que la presión sea menor que con la válvula cerrada.'], answer: 2, why: 'El alivio añade una salida. En este banco descarga hacia 101 kPa absolutos y no genera vacío. La presión depende del balance entre aporte y salida.' },
    { question: 'El transmisor entrega 12 mA con escala lineal 0–400 kPa absolutos ↔ 4–20 mA. ¿Qué presión representa?', options: ['300 kPa absolutos.', '200 kPa absolutos.', '12 kPa absolutos.'], answer: 1, why: '12 mA está a mitad de camino entre 4 y 20 mA, por lo que representa la mitad de 400 kPa. La señal no es la potencia de la bobina.' },
    { question: 'Conectas transmisor de presión, motor de banda y regla aliviar al superar el umbral. ¿Qué falta?', options: ['Un actuador que realmente descargue el depósito.', 'Solo cambiar la unidad de rpm a kPa.', 'Nada: cualquier actuador cierra cualquier lazo.'], answer: 0, why: 'Mover esta banda no modifica la presión del depósito. La coherencia depende del proceso físico, no solo de que existan tres componentes.' },
    { question: 'El sensor da una señal correcta, pero la etapa de potencia está desconectada. ¿Puede la orden garantizar una acción física?', options: ['Sí: la información del sensor aporta toda la energía.', 'Sí: un controlador hace girar cualquier motor sin fuente.', 'No: una orden no sustituye el suministro y la etapa de potencia.'], answer: 2, why: 'La señal comunica una decisión. El actuador necesita energía y una etapa adecuada; en un sistema real también deben verificarse protecciones y respuesta.' },
    { question: 'El simulador detiene la banda sin distancia de frenado y limita el depósito a 400 kPa. ¿Cómo usar estos resultados?', options: ['Como garantía de parada y protección en una instalación.', 'Como predicción didáctica; hay que considerar inercia, retardos y protecciones reales.', 'Como prueba de que la presión nunca puede superar 400 kPa en ningún equipo.'], answer: 1, why: 'Los límites y respuestas ideales ayudan a entender el lazo, no certifican seguridad ni dimensionan componentes reales.' }
  ],
  source: 'Tema II · Integración Sensor–Controlador–Actuador. Modelos didácticos locales, sin instrucciones de cableado industrial.'
};
