// content/tema-01.js
window.NEXO.content.sensores = {
  title: 'El mundo físico.\nEn forma de señal.',
  subtitle: 'De un objeto frente a un haz de luz a la presión dentro de una tubería. Experimenta cómo medimos lo que ocurre.',
  objectives: ['Explicar la transducción y distinguir medir de detectar.', 'Comparar tecnologías y reconocer cuándo dejan de funcionar.', 'Interpretar curvas, umbrales y referencias antes de elegir un sensor.'],
  sections: [
    { title: 'De la magnitud a la señal', tags: ['Concepto de sensor', 'Discreta y analógica'], paragraphs: [
      'Un sensor detecta una magnitud física del entorno y la convierte en una señal interpretable por un controlador. Esa conversión es la transducción: temperatura → resistencia, luz → corriente o presión → deformación → señal eléctrica.',
      'El elemento sensible no siempre entrega directamente 0–10 V o 4–20 mA. Un circuito de acondicionamiento amplifica, filtra, linealiza o convierte su señal. Un transmisor puede convertir la medida en una señal industrial normalizada.',
      'Una detección discreta entrega dos estados lógicos: presencia/ausencia o 1/0. Es simple para contar piezas o activar un límite, pero no indica cuánto mide la magnitud. El 1 lógico no implica que la tensión sea 1 V: una entrada industrial puede trabajar a 24 V.',
      'Una salida analógica representa un valor continuo dentro de un rango: permite regular, analizar tendencias y detectar desviaciones. Requiere escala, calibración y atención al ruido. El controlador suele digitalizarla mediante un ADC, con resolución finita.',
      'En un lazo 4–20 mA, 4 mA representa el mínimo válido (cero vivo), no ausencia de alimentación. Una corriente cercana a cero puede indicar una falla; el diagnóstico concreto depende del transmisor. Fuera del rango no se debe extrapolar sin conocer el equipo.'
    ], challenge: 'Fija el umbral en 60 %. Cambia el nivel de 59 a 61 %. ¿Qué información conserva la salida analógica que pierde la discreta?' },
    { title: 'Luz, detección y materiales', tags: ['Sensores ópticos', 'Emisor', 'Receptor', 'Lentes', 'Circuito de salida', 'Barrera', 'Reflexivo', 'Difuso', 'Proximidad', 'Capacitivo', 'Inductivo', 'Infrarrojo'], paragraphs: [
      'Los sensores ópticos detectan la interrupción o reflexión de luz. El emisor suele ser un LED visible, infrarrojo o una fuente láser. La modulación y la detección selectiva ayudan a rechazar iluminación ajena, pero no garantizan inmunidad absoluta al sol o a interferencias.',
      'El receptor, fotodiodo o fototransistor, transforma la luz en corriente. La respuesta espectral debe ser compatible con el emisor. La electrónica amplifica y compara esa señal. Las lentes orientan el haz y el campo de visión; mejoran alcance y selectividad, pero exigen alineación y limpieza.',
      'El circuito de salida adapta el resultado al controlador. En una salida DC de transistor, NPN absorbe corriente hacia 0 V y PNP suministra corriente desde positivo; la entrada del controlador debe ser compatible. NO/NC describe la lógica de activación, no el tipo de transistor. En ópticos, Light-ON/Dark-ON debe distinguirse de “objeto presente” porque depende de la geometría.',
      'Barrera: emisor y receptor enfrentados en carcasas distintas. Detecta al interrumpirse el haz, suele ofrecer mayor alcance y margen óptico; exige alineación y cableado a ambos lados. Retroreflectivo: emisor y receptor juntos, con reflector catadióptrico al frente. Se instala y cablea desde un lado; un objeto brillante puede devolver luz y confundirse con el reflector. La polarización ayuda, según el modelo.',
      'Difuso: el propio objeto devuelve la luz al receptor, sin reflector separado. El alcance suele ser menor y depende del tamaño, color, orientación y acabado. Las variantes con supresión de fondo reducen algunos problemas, pero no vuelven irrelevante el material.',
      'Proximidad significa detección sin contacto. La distancia de conmutación depende del sensor y del objeto de referencia. La histéresis separa el punto de activación del de desactivación, evitando cambios repetidos por vibración cerca del límite.',
      'Capacitivo: el objeto modifica la capacitancia del campo sensible. Detecta metales y también plástico, madera, granos y líquidos. Puede detectar nivel a través de una pared aislante, según espesor, constante dieléctrica y ajuste. Humedad, depósitos o la propia pared pueden provocar detecciones no deseadas.',
      'Inductivo: un oscilador produce un campo electromagnético. En el metal se inducen corrientes de Foucault que alteran o amortiguan la oscilación. Detecta metales; el alcance convencional suele ser mayor en acero que en aluminio o cobre. Hay modelos de factor 1. Es robusto ante suciedad y humedad dentro de su grado de protección, no inmune a cualquier entorno.',
      'Infrarrojo activo reflectivo: emite IR y analiza la reflexión. El color, brillo, transparencia, distancia e iluminación afectan la medida. No equivale al infrarrojo térmico pasivo: este detecta radiación emitida por los cuerpos; un PIR suele detectar cambios de radiación, no distancia. Esta distinción amplía la descripción térmica de la antología.'
    ], challenge: 'Compara una pieza clara con una oscura en modo difuso. Luego cambia el mismo material entre inductivo, capacitivo e infrarrojo: ¿qué principio explica la diferencia?' },
    { title: 'Temperatura y presión', tags: ['Temperatura', 'Termistor', 'NTC y PTC', 'RTD', 'Termopar', 'Presión'], paragraphs: [
      'Un sensor de temperatura utiliza, entre otros principios, la variación de resistencia o una fuerza electromotriz termoeléctrica. Sensibilidad, exactitud, estabilidad y tiempo de respuesta no significan lo mismo; la vaina, el montaje y el intercambio de calor también importan.',
      'El termistor es un elemento resistivo semiconductor. Suele ser económico, sensible y no lineal, con un intervalo práctico de aproximadamente −50 a 150 °C en muchos modelos, no en todos. Una pieza pequeña puede responder rápido, pero el encapsulado cambia esa respuesta.',
      'NTC: su resistencia disminuye al subir la temperatura. Se utiliza para medir y compensar temperatura; el banco usa un NTC de 10 kΩ a 25 °C y el modelo Beta. PTC: su resistencia aumenta. Los PTC cerámicos de conmutación muestran una subida pronunciada cerca de una temperatura característica, útil para protección y autorregulación. No todos los PTC tienen la misma curva ni sustituyen una protección certificada.',
      'RTD: mide la variación de resistencia de un metal. El Pt100 de platino presenta 100 Ω a 0 °C. La pendiente aproximada de 0,385 Ω/°C es útil en un intervalo acotado, no como ley exacta de −200 a 850 °C. El banco utiliza Callendar–Van Dusen. La resistencia de los cables, el autocalentamiento y la conexión a 2, 3 o 4 hilos afectan el resultado. Su estabilidad y exactitud suelen ser buenas; costo y respuesta dependen de la construcción.',
      'Termopar: dos conductores diferentes generan una fuerza electromotriz por efecto Seebeck cuando existen diferencias de temperatura. No mide una temperatura absoluta sin referencia. La compensación de junta fría utiliza la temperatura de los terminales para interpretar la tensión. Es robusto y cubre rangos amplios según tipo y montaje, aunque exige tratar señales pequeñas y suele ser menos exacto que un RTD adecuado.',
      'Presión: una membrana se deforma por la diferencia de presión entre sus caras. En un sensor piezorresistivo cambia la resistencia de elementos sensibles, habitualmente en un puente; en uno capacitivo cambia la separación o geometría de electrodos y con ello la capacitancia. La electrónica acondiciona la señal para entregarla al controlador.',
      'La presión absoluta se referencia al vacío ideal. La manométrica resta la presión atmosférica local y puede ser negativa sin que la presión absoluta lo sea. La diferencial resta la presión de otro punto del proceso. Elegir la referencia equivocada cambia el significado de la lectura aunque el sensor funcione correctamente.',
      'Una alarma por umbral es una condición lógica, no una válvula de seguridad ni una protección certificada. La selección industrial debe considerar rango, sobrepresión, compatibilidad del fluido y temperatura. El banco es educativo y no sirve para dimensionar equipos reales.'
    ], challenge: 'Lleva el NTC fuera de rango sin hacer lo mismo con el termopar. En presión, conserva la presión absoluta y cambia la referencia: explica por qué cambia la lectura.' },
    { title: 'Comprueba tu criterio', tags: [], paragraphs: ['Resuelve casos prácticos. Cada respuesta incluye una explicación; puedes volver a intentarlo. La puntuación es una ayuda de estudio, no una calificación oficial ni una prueba de certificación.'] }
  ],
  source: 'Antología de Sistemas Programables, Instituto Tecnológico Superior de Uruapan · Unidad 1. Organización de cobertura: rúbrica del Tema I. Modelos y aclaraciones didácticas explícitos en cada banco.',
  note: 'Fases 2–4 implementadas. Validación técnica y revisión visual omitidas por solicitud; pendiente auditoría final.'
};
window.NEXO.content.sensorQuiz = [
  { question: 'Un fotodiodo recibe luz y produce una corriente. ¿Qué representa ese cambio?', options: ['Transducción', 'Realimentación mecánica', 'Conmutación de una carga de potencia'], answer: 0, why: 'La transducción convierte una magnitud física en otra señal utilizable. El fotodiodo convierte luz en corriente; todavía puede ser necesario acondicionarla.' },
  { question: 'Para conocer cuánto líquido queda, no solo si superó un límite, ¿qué salida conviene?', options: ['Una discreta NO', 'Una analógica correctamente escalada', 'Una discreta NC sin umbral'], answer: 1, why: 'La salida analógica conserva información del nivel dentro del rango. Un interruptor de nivel solo responde a una condición, aunque se invierta NO/NC.' },
  { question: 'En un transmisor 4–20 mA de 0–100 %, ¿qué significa 4 mA en operación normal?', options: ['Siempre un cable roto', 'El máximo del rango', 'El mínimo válido de la escala'], answer: 2, why: '4 mA es el cero vivo. Una corriente cercana a 0 mA puede indicar falla, pero los umbrales de diagnóstico deben consultarse en la documentación.' },
  { question: '¿Qué componente óptico convierte la luz recibida en una señal eléctrica?', options: ['La lente', 'El fotodiodo o fototransistor', 'El reflector catadióptrico'], answer: 1, why: 'El receptor convierte luz en corriente. La lente dirige la luz y el reflector devuelve el haz; ninguno sustituye al elemento fotosensible.' },
  { question: '¿Qué combinación describe un sensor de barrera?', options: ['Emisor y receptor separados; el objeto interrumpe el haz', 'Un solo cuerpo sin reflector y reflexión en el objeto', 'Un campo que detecta exclusivamente metal'], answer: 0, why: 'En barrera el emisor y el receptor están enfrentados. El difuso utiliza la reflexión del objeto; el principio exclusivamente metálico corresponde al inductivo.' },
  { question: 'Una pieza negra deja de detectarse al sustituir una blanca en modo difuso. ¿Qué explicación es razonable?', options: ['Todos los sensores solo detectan blanco', 'La pieza cambió la frecuencia de alimentación', 'Regresa menos luz útil al receptor'], answer: 2, why: 'La reflectancia y geometría cambian el margen óptico. La solución puede requerir otro ajuste, tecnología o disposición, no asumir un fallo del controlador.' },
  { question: 'Necesitas detectar agua a través de una pared plástica fina. ¿Qué tecnología explorarías primero?', options: ['Inductiva convencional', 'Capacitiva con ajuste adecuado', 'Barrera sin receptor'], answer: 1, why: 'El campo capacitivo puede detectar el cambio de permitividad a través de una pared aislante. Hay que comprobar espesor, humedad, depósitos y sensibilidad en el equipo real.' },
  { question: 'Un inductivo detecta acero pero no una pieza de madera. ¿Por qué?', options: ['El principio requiere corrientes inducidas en un objeto metálico', 'La madera siempre es transparente', 'Falta una lente'], answer: 0, why: 'Las corrientes de Foucault del objeto metálico alteran el oscilador. La madera no ofrece la respuesta de un blanco metálico; color y lentes no explican el principio.' },
  { question: '¿Qué consigue la histéresis en una detección de proximidad?', options: ['Medir cualquier material', 'Eliminar todas las interferencias', 'Separar los puntos de conexión y desconexión'], answer: 2, why: 'La separación reduce conmutaciones repetidas por pequeñas variaciones cerca del límite. No cambia por sí sola los materiales detectables ni suprime toda interferencia.' },
  { question: 'Al calentar un NTC dentro de su rango, ¿qué sucede con su resistencia?', options: ['Aumenta siempre linealmente', 'Disminuye de forma no lineal', 'Se mantiene en 100 Ω'], answer: 1, why: 'El coeficiente del NTC es negativo. Un Pt100 tiene 100 Ω a 0 °C, y un PTC aumenta su resistencia al elevarse la temperatura.' },
  { question: 'Un Pt100 ideal a 0 °C presenta aproximadamente…', options: ['100 Ω', '100 mA', '0 Ω'], answer: 0, why: 'Pt indica platino y 100 la resistencia nominal a 0 °C. La medición real depende también de tolerancia, cableado y autocalentamiento.' },
  { question: '¿Por qué importa la junta fría de un termopar?', options: ['Porque elimina la necesidad de dos metales', 'Porque la tensión depende también de la temperatura de referencia', 'Porque transforma el termopar en NTC'], answer: 1, why: 'La fuerza electromotriz se interpreta considerando la referencia. La compensación de junta fría incorpora la temperatura de los terminales para estimar la del punto de medida.' },
  { question: 'P absoluta = 90 kPa y P atmosférica = 100 kPa. ¿Cuál es la manométrica?', options: ['190 kPa', '90 kPa', '−10 kPa'], answer: 2, why: 'Pman = Pabs − Patm = −10 kPa. Es un vacío relativo al ambiente, no una presión absoluta negativa.' },
  { question: 'NPN/PNP y NO/NC describen…', options: ['La misma característica con nombres distintos', 'Topología eléctrica y lógica de activación, respectivamente', 'El color del LED y el alcance de la lente'], answer: 1, why: 'NPN/PNP se refiere a cómo circula la corriente en la salida. NO/NC se refiere al estado lógico respecto a una condición definida; son decisiones diferentes.' },
  { question: 'Una alarma de presión del simulador se activa. ¿Qué se puede concluir?', options: ['Que se cumple la regla de umbral del modelo', 'Que la instalación real ya tiene protección certificada', 'Que la válvula real necesariamente se abrió'], answer: 0, why: 'Solo se ha evaluado una condición del modelo. Protección industrial, accionamiento y seguridad funcional requieren equipos y diseño específicos.' }
];
