// content/tema-02.js
window.NEXO.content.actuadores = {
  title: 'La señal da\nel siguiente paso.',
  subtitle: 'Giro, desplazamiento, fuerza, luz y sonido. Explora cómo una orden gobierna la energía que transforma un proceso.',
  objectives: ['Distinguir una señal de mando de la alimentación de potencia.', 'Relacionar impulsos, velocidad y posición en motores.', 'Explicar la conversión de movimiento y la fuerza de los fluidos.'],
  sections: [
    { title: 'De la orden a la energía', paragraphs: [
      'Un actuador recibe una orden del controlador y utiliza energía para provocar una acción física: movimiento, fuerza, calor, luz o sonido. El sensor informa del proceso; el actuador lo modifica. Su salida útil no es la señal de mando, sino el efecto producido.',
      'Una salida lógica no debe confundirse con la alimentación de una carga. Un driver, relé, contactor o etapa de potencia permite que una orden de baja potencia gobierne una fuente capaz de alimentar el actuador. El tipo de interfaz depende de corriente, tensión, frecuencia de maniobra, aislamiento y protecciones.',
      'Los actuadores eléctricos convierten electricidad en acción. Son fáciles de integrar y pueden ofrecer precisión y buena eficiencia, pero mantenimiento y control dependen del tipo: un motor con escobillas no tiene el mismo desgaste que uno sin ellas. La fuerza depende del motor y su transmisión; “eléctrico = poca fuerza” no es una regla universal.',
      'La clasificación de la antología agrupa mecánicos o neumáticos. Aquí los distinguimos: un mecanismo transforma o transmite movimiento; un actuador neumático convierte la energía del aire comprimido en fuerza y desplazamiento. Un husillo no genera energía: puede ser impulsado por un motor eléctrico.',
      'Los neumáticos suelen ser rápidos y simples en maniobras de sujeción o expulsión. La compresibilidad del aire y las cargas influyen en precisión y rigidez; necesitan compresor, tratamiento del aire y mantenimiento. El escape puede producir ruido. Trabajar en atmósferas inflamables exige componentes y certificación adecuados, no basta con utilizar aire.',
      'Los hidráulicos emplean líquido a presión y ofrecen alta densidad de fuerza y rigidez. Requieren bomba, depósito, válvulas, conducciones y control de contaminación. El costo, mantenimiento, fugas y energía acumulada son parte de la selección. Su potencia no surge de la nada: procede de la fuente que acciona la bomba.'
    ] },
    { title: 'Siete formas de actuar', paragraphs: [
      'Cada dispositivo tiene una fuente de energía, un principio de conversión y una forma de control. Selecciona uno y compara qué sucede si existe orden pero falta alimentación de potencia. Las ilustraciones representan estados; no son esquemas de conexión para equipos reales.',
      'Los elementos inductivos requieren estrategias de protección frente a sobretensiones de desconexión. La protección depende de si la carga es DC o AC y del accionamiento; un diodo de rueda libre no es una receta universal para todas las cargas.'
    ] },
    { title: 'Impulsos, dirección y velocidad', paragraphs: [
      'El motor paso a paso divide la vuelta en posiciones discretas. Su driver energiza las fases en una secuencia: el campo magnético cambia y el rotor sigue la posición de equilibrio. En un driver STEP/DIR, los impulsos solicitan pasos y la entrada de dirección determina el sentido; no se conecta una salida lógica directamente a la bobina.',
      'Para un paso de 1,8°, 200 pasos completos corresponden a una vuelta. La velocidad ideal en rpm es frecuencia de pasos × ángulo por paso / 6. Invertir la secuencia invierte el giro. El micropaso interpola corrientes para suavizar el movimiento, pero más subdivisiones de mando no garantizan igual exactitud mecánica.',
      'El par disponible, la inercia, la aceleración y las resonancias limitan la velocidad. Si se exige demasiado, puede perder pasos. En lazo abierto, contar impulsos no prueba que el eje haya llegado: hace falta referencia o realimentación para comprobarlo. Es útil en dosificadores, impresoras, mesas pequeñas y posicionamiento de cargas compatibles.',
      'La comparación AC/DC de este banco utiliza un motor AC de inducción de jaula y un motor DC con escobillas. No pretende describir todos los motores AC, los BLDC o los servos con una sola regla.',
      'El motor de inducción genera un campo giratorio mediante alimentación alterna; la velocidad síncrona depende de frecuencia y polos. En régimen motor, el rotor gira algo más lento por el deslizamiento. Un variador modifica frecuencia y tensión dentro de las condiciones de diseño. Es común en ventiladores, extractores, mezcladoras y bandas continuas.',
      'En el DC con escobillas, conmutador y escobillas cambian la corriente del rotor y mantienen el par. Para un motor de imanes permanentes, la velocidad sin carga se relaciona aproximadamente con la tensión media, mientras la corriente se vincula al par. PWM regula el mando y un puente H permite invertir. Es útil en transportadores pequeños o mecanismos de alimentación; no convierte automáticamente el equipo en un servosistema.'
    ] },
    { title: 'Movimiento, presión y flujo', paragraphs: [
      'Un actuador mecánico transforma movimiento: husillo-tuerca y piñón-cremallera convierten giro en traslación. En el husillo, una vuelta produce un avance igual a su paso de avance; en la cremallera, el desplazamiento ideal es el ángulo en radianes por el radio primitivo del piñón. Holgura, fricción, eficiencia y rigidez alteran el comportamiento real.',
      'Estos mecanismos se usan para elevar plataformas, trasladar materiales y posicionar mesas. Algunos husillos pueden ser autoblocantes bajo ciertas condiciones; no todos son irreversibles y no debe asumirse que sostendrán una carga suspendida sin una protección adecuada.',
      'En un cilindro hidráulico, la fuerza ideal depende de presión diferencial y área efectiva: F = ΔP × A. La velocidad ideal depende del caudal: v = Q/A. Aumentar el área produce más fuerza a igual presión, pero menor velocidad a igual caudal. La carga, pérdidas, válvulas y límites de la bomba afectan el resultado real.',
      'En simple efecto el fluido actúa en un sentido y el retorno lo realiza un resorte o la gravedad. En doble efecto se presurizan alternativamente las dos cámaras. El lado del vástago tiene menor área efectiva: a igual presión produce menor fuerza y a igual caudal mayor velocidad de retroceso, si las condiciones lo permiten.',
      'Los actuadores hidráulicos lineales son cilindros. Los rotativos incluyen motores de giro continuo y actuadores de giro limitado. El desplazamiento volumétrico relaciona caudal con velocidad de giro; el par ideal depende de la presión y del volumen por vuelta. Se utilizan en prensas, maquinaria de construcción, elevación y accionamientos de alto esfuerzo.',
      'Una válvula solenoide usa una bobina para crear un campo magnético que desplaza un émbolo. En el ejemplo 2/2 normalmente cerrado y de acción directa, la bobina levanta el cierre contra un resorte y abre un paso. Al desenergizar, el resorte lo devuelve. “2/2” significa dos vías y dos posiciones.',
      'Una bobina energizada no bombea fluido: abrir el paso solo permite flujo si existen condiciones de presión apropiadas. Hay válvulas normalmente abiertas, biestables y pilotadas; estas últimas pueden requerir una presión diferencial mínima. La selección considera fluido, presión, caudal, material, temperatura y ciclo de trabajo de la bobina.',
      'Ejemplo industrial: permitir agua en una etapa de llenado cuando el controlador lo ordena. El cierre normalmente cerrado ante pérdida de alimentación es una característica del ejemplo, no una garantía universal de seguridad funcional.'
    ] },
    { title: 'Elegir para un trabajo real', paragraphs: ['Seleccionar empieza por describir qué debe ocurrir, no por elegir el dispositivo más potente. Comprueba energía disponible, carga, precisión y velocidad; después compara mantenimiento, espacio y costo total.', 'Potencia: debe cubrir el trabajo sin exceder límites térmicos. Controlabilidad: debe responder al tipo de orden requerido. Peso y volumen: deben caber y no añadir inercia innecesaria. Precisión: importa el error admisible, no solo el número de pasos. Velocidad: considera aceleración y carga. Mantenimiento: valora desgaste y acceso. Costo: incluye fuente, driver, instalación y operación, no solo la compra.', 'El selector es una guía con reglas visibles. Descarta fuentes incompatibles y explica por qué unas alternativas resultan más apropiadas que otras. Sus puntuaciones son educativas: no sustituyen cálculos de dimensionamiento o especificaciones del fabricante.', 'Las once estaciones muestran contextos diferentes: bandas, robots, bombeo, control de líquidos, electroválvulas, alarmas, ventiladores, extractores, mezcladoras, posicionamiento y procesos automatizados. Una planta necesita combinaciones coordinadas, no un actuador universal.'] }
  ],
  source: 'Antología de Sistemas Programables · Unidad 2: Actuadores y rúbrica acumulativa del Tema II. Modelos ideales y limitaciones declarados en cada banco.',
  note: 'Aprende qué hace cada actuador, prueba sus límites y elige uno para una situación industrial.'
};
window.NEXO.content.actuatorDevices = [
  { id: 'dc', name: 'Motor DC', code: 'M01', effect: 'Giro', energy: 'Eléctrica → mecánica', driver: 'Puente H / PWM', description: 'Ejemplo de motor de imanes permanentes con escobillas. La interacción de los campos produce par; la conmutación mantiene su dirección.', advantage: 'Control de velocidad sencillo mediante tensión media; inversión con accionamiento compatible.', limitation: 'Las escobillas se desgastan. Carga y pérdidas modifican velocidad y corriente.', application: 'Rodillos de alimentación y pequeñas bandas de velocidad variable.', action: 'Solicitar giro', on: 'La etapa aplica energía al motor: el rotor cambia de posición.', off: 'Sin energía aplicada no hay par motor. El frenado y la inercia no se modelan.' },
  { id: 'ac', name: 'Motor AC', code: 'M02', effect: 'Giro continuo', energy: 'Eléctrica → mecánica', driver: 'Contactor / variador', description: 'En un motor de inducción, el campo giratorio induce corriente en el rotor y genera par. En régimen motor necesita deslizamiento.', advantage: 'Construcción robusta y uso extendido en funcionamiento continuo.', limitation: 'Regular velocidad requiere un accionamiento apropiado; no basta bajar arbitrariamente la tensión.', application: 'Ventiladores, extractores, mezcladoras y transportadores continuos.', action: 'Solicitar marcha', on: 'El accionamiento alimenta el motor. El campo giratorio produce movimiento.', off: 'No se aplica alimentación; el paro real depende de inercia y estrategia de frenado.' },
  { id: 'stepper', name: 'Motor paso a paso', code: 'M03', effect: 'Posición discreta', energy: 'Eléctrica → mecánica', driver: 'Driver de corriente por fases', description: 'Una secuencia de corrientes orienta el campo del estator. Cada paso completo solicita un incremento angular definido.', advantage: 'Control incremental útil en mecanismos de posicionamiento compatibles.', limitation: 'Puede perder pasos por carga o aceleración excesivas; contar órdenes no confirma posición real.', application: 'Dosificadores, impresoras y mesas de posicionamiento pequeñas.', action: 'Solicitar un paso', on: 'Se ha solicitado una nueva posición de equilibrio; consulta el banco detallado para contar impulsos.', off: 'Sin corriente de fase no hay par de mantenimiento activo; puede existir par de detención residual.' },
  { id: 'solenoid', name: 'Válvula solenoide', code: 'Y01', effect: 'Paso de fluido', energy: 'Eléctrica → fuerza magnética', driver: 'Salida de potencia compatible con bobina', description: 'La bobina desplaza un émbolo que modifica un paso. El ejemplo es normalmente cerrado de acción directa.', advantage: 'Conmutación eléctrica de líquidos o gases en sistemas automatizados.', limitation: 'Tensión, presión, fluido y servicio continuo deben ser compatibles; abrir no garantiza flujo.', application: 'Admisión de agua en una secuencia de llenado.', action: 'Energizar bobina', on: 'Bobina energizada: paso abierto en este ejemplo. Se supone presión favorable para la indicación.', off: 'Bobina sin energía: el resorte cierra el paso del ejemplo NC.' },
  { id: 'pump', name: 'Motobomba', code: 'P01', effect: 'Transferencia de líquido', energy: 'Eléctrica → energía hidráulica', driver: 'Contactor o variador del motor', description: 'Un motor acciona una bomba. En el ejemplo centrífugo, el impulsor transfiere energía al líquido y la carcasa ayuda a convertirla en presión.', advantage: 'Permite transportar líquidos entre puntos y alimentar procesos.', limitation: 'El caudal depende de la curva bomba-sistema; requiere condiciones de aspiración adecuadas. No todas son autocebantes o sumergibles.', application: 'Recirculación, suministro y evacuación de agua.', action: 'Solicitar bombeo', on: 'Impulsor accionado. Se suponen líquido disponible, cebado correcto y circuito abierto; no se calcula caudal.', off: 'No se aporta energía desde el motor; no se modelan retorno ni flujo por gravedad.' },
  { id: 'pilot', name: 'Piloto luminoso', code: 'H01', effect: 'Luz', energy: 'Eléctrica → luminosa', driver: 'Salida y limitación de corriente apropiadas', description: 'Un indicador, por ejemplo LED industrial, convierte energía eléctrica en luz para comunicar un estado.', advantage: 'Señalización visual simple e inmediata.', limitation: 'El color no debe ser la única información y el encendido no prueba por sí solo el estado mecánico de una máquina.', application: 'Indicación de marcha, espera o condición de un proceso.', action: 'Encender piloto', on: 'Piloto encendido: señal luminosa acompañada de texto.', off: 'Piloto apagado: no hay indicación luminosa en el modelo.' },
  { id: 'buzzer', name: 'Zumbador', code: 'H02', effect: 'Sonido', energy: 'Eléctrica → acústica', driver: 'Salida compatible con zumbador activo o driver de tono', description: 'Puede ser electromagnético o piezoeléctrico. Un modelo activo incluye oscilador; uno pasivo requiere una señal alternante de excitación.', advantage: 'Llama la atención aunque no se esté mirando el panel.', limitation: 'Ruido de fondo, nivel sonoro y accesibilidad importan. La vista ofrece aviso textual y el audio es opcional.', application: 'Alarmas y avisos al finalizar una etapa.', action: 'Activar aviso', on: 'Aviso activo visualmente. El botón de audio reproduce solo una muestra breve y opcional.', off: 'Aviso desactivado.' }
];
